//
// Copyright 2017 Amazon.com, Inc. or its affiliates (Amazon). All Rights Reserved.
//
// Code generated by AWS Mobile Hub. Amazon gives unlimited permission to 
// copy, distribute and modify it.
//
// Source code generated from template: aws-my-sample-app-android v0.14
//
package com.finalyearproject.dan.ocraccountingapp.mobile;

import com.amazonaws.regions.Regions;

/**
 * This class defines constants for the developer's resource
 * identifiers and API keys. This configuration should not
 * be shared or posted to any public source code repository.
 */
public class AWSConfiguration {
    // AWS MobileHub user agent string
    public static final String AWS_MOBILEHUB_USER_AGENT =
        "MobileHub 50885f37-d1f0-4765-af77-a7fba6cb64ce aws-my-sample-app-android-v0.14";
    // AMAZON COGNITO
    public static final Regions AMAZON_COGNITO_REGION =
      Regions.fromName("eu-west-1");
    public static final String AMAZON_COGNITO_IDENTITY_POOL_ID =
        "eu-west-1:5b2f5614-f4f6-4ba5-8853-29768fe01899";
    public static final String AMAZON_COGNITO_USER_POOL_ID =
        "eu-west-1_bSplAxKaH";
    public static final String AMAZON_COGNITO_USER_POOL_CLIENT_ID =
        "4qi5mafu3hh6ud9nc6lgqvb77j";
    public static final String AMAZON_COGNITO_USER_POOL_CLIENT_SECRET =
        "1jc70p03uk666k19jf3qcnjkpk8rqep7cjr9rsulhh51c6vl80qu";
}
