//
// Copyright 2017 Amazon.com, Inc. or its affiliates (Amazon). All Rights Reserved.
//
// Code generated by AWS Mobile Hub. Amazon gives unlimited permission to 
// copy, distribute and modify it.
//
// Source code generated from template: aws-my-sample-app-android v0.14
//
package com.finalyearproject.dan.ocraccountingapp.signup.util;

import android.app.Activity;
import android.app.AlertDialog;
import android.widget.EditText;

public final class ViewHelper {

    public static String getStringValue(final Activity activity, final int viewId) {
        if (null == activity) {
            return "";
        }

        return ((EditText) activity.findViewById(viewId)).getText().toString();
    }

    public static void showDialog(final Activity activity, final String title, final String body) {
        if (null == activity) {
            return;
        }

        final AlertDialog.Builder builder = new AlertDialog.Builder(activity);
        builder.setTitle(title);
        builder.setMessage(body);
        builder.setNeutralButton("OK", null);
        builder.show();
    }
}
